#!/usr/bin/env bash
 
# Touchpad 
# List touchpad settings w/ synclient -l

# Disable tap to click
synclient MaxTapTime=0

# Disable two finger horizontal scroll (unless shift held)
synclient HorizTwoFingerScroll=0

# Prevent palm tapping touchpad? Apparently a fix on 17.10
synclient PalmDetect=1

# Disable touchpad while typing
#syndaemon -d -t -i 0.5

# Keyboard 

# Set keyboard layout
setxkbmap -layout us -variant colemak -option "caps:escape"

# Disable insert key (doesn't work on T500)
xmodmap -e "keycode 118 = "

